# Generated by Django 3.2.6 on 2021-12-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('avg_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('avg_price', models.IntegerField()),
            ],
        ),
    ]
